package com.hs.alice.domain;

// Generated 2013. 4. 10 오전 10:19:22 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.hs.alice.core.AliceCore;

/**
 * AuthRoleUserMap generated by hbm2java
 */
public class AuthRoleUserMap implements java.io.Serializable {

	private static final long serialVersionUID = AliceCore.SERIAL_VERSION_UID;

    private static final Log logger = LogFactory.getLog(AuthRoleUserMap.class);

	private BigDecimal mapid;
	private AuthUser authUser;
	private AuthRole authRole;

	public AuthRoleUserMap() {
	}

	public AuthRoleUserMap(BigDecimal mapid, AuthUser authUser,
			AuthRole authRole) {
		this.mapid = mapid;
		this.authUser = authUser;
		this.authRole = authRole;
	}

	public BigDecimal getMapid() {
		return this.mapid;
	}

	public void setMapid(BigDecimal mapid) {
		this.mapid = mapid;
	}

	public AuthUser getAuthUser() {
		return this.authUser;
	}

	public void setAuthUser(AuthUser authUser) {
		this.authUser = authUser;
	}

	public AuthRole getAuthRole() {
		return this.authRole;
	}

	public void setAuthRole(AuthRole authRole) {
		this.authRole = authRole;
	}

	@Override
	public String toString() {
		return "AuthRoleUserMap [mapid=" + mapid + ", authUser=" + authUser.getUserid()
				+ ", authRole=" + authRole.getRoleid() + "]";
	}

	
}
