package com.hs.alice.sr.domain;

// Generated 2013. 4. 29 오후 2:46:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * SrInstallCodeVersion generated by hbm2java
 */
@Entity
@Table(name = "SR_INSTALL_CODE_VERSION", schema = "ALICE")
public class SrInstallCodeVersion implements java.io.Serializable {

	private int id;
	private SrInstallCodeProduct srInstallCodeProduct;
	private String value;
	private Set<SrInstall> srInstalls = new HashSet<SrInstall>(0);

	public SrInstallCodeVersion() {
	}

	public SrInstallCodeVersion(int id) {
		this.id = id;
	}

	public SrInstallCodeVersion(int id,
			SrInstallCodeProduct srInstallCodeProduct, String value,
			Set<SrInstall> srInstalls) {
		this.id = id;
		this.srInstallCodeProduct = srInstallCodeProduct;
		this.value = value;
		this.srInstalls = srInstalls;
	}

	@Id
	@TableGenerator(name="TABLE_GEN", table="ALICE_ID", pkColumnName="ID_NAME", 
		valueColumnName="ID_COUNT", pkColumnValue="SR_INSTALL_CODE_VERSION", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.TABLE, generator="TABLE_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT")
	public SrInstallCodeProduct getSrInstallCodeProduct() {
		return this.srInstallCodeProduct;
	}

	public void setSrInstallCodeProduct(
			SrInstallCodeProduct srInstallCodeProduct) {
		this.srInstallCodeProduct = srInstallCodeProduct;
	}

	@Column(name = "VALUE", length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "srInstallCodeVersion")
	public Set<SrInstall> getSrInstalls() {
		return this.srInstalls;
	}

	public void setSrInstalls(Set<SrInstall> srInstalls) {
		this.srInstalls = srInstalls;
	}

}
