package com.hs.alice.sr.domain;

// Generated 2013. 4. 29 오후 2:46:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * SrInstallInfo generated by hbm2java
 */
@Entity
@Table(name = "SR_INSTALL_INFO", schema = "ALICE")
public class SrInstallInfo implements java.io.Serializable {

	private int id;
	private SrInstall srInstall;
	private SrInstallInfoCodeValue srInstallInfoCodeValue;
	private SrInstallInfoCodeName srInstallInfoCodeName;

	public SrInstallInfo() {
	}

	public SrInstallInfo(int id) {
		this.id = id;
	}

	public SrInstallInfo(int id, SrInstall srInstall,
			SrInstallInfoCodeValue srInstallInfoCodeValue,
			SrInstallInfoCodeName srInstallInfoCodeName) {
		this.id = id;
		this.srInstall = srInstall;
		this.srInstallInfoCodeValue = srInstallInfoCodeValue;
		this.srInstallInfoCodeName = srInstallInfoCodeName;
	}

	@Id
	@TableGenerator(name="TABLE_GEN", table="ALICE_ID", pkColumnName="ID_NAME", 
		valueColumnName="ID_COUNT", pkColumnValue="SR_INSTALL_INFO", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.TABLE, generator="TABLE_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INSTALL")
	public SrInstall getSrInstall() {
		return this.srInstall;
	}

	public void setSrInstall(SrInstall srInstall) {
		this.srInstall = srInstall;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VALUE")
	public SrInstallInfoCodeValue getSrInstallInfoCodeValue() {
		return this.srInstallInfoCodeValue;
	}

	public void setSrInstallInfoCodeValue(
			SrInstallInfoCodeValue srInstallInfoCodeValue) {
		this.srInstallInfoCodeValue = srInstallInfoCodeValue;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NAME")
	public SrInstallInfoCodeName getSrInstallInfoCodeName() {
		return this.srInstallInfoCodeName;
	}

	public void setSrInstallInfoCodeName(
			SrInstallInfoCodeName srInstallInfoCodeName) {
		this.srInstallInfoCodeName = srInstallInfoCodeName;
	}

}
