package com.hs.alice.sr.domain;

// Generated 2013. 4. 29 오후 2:46:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * SrUserCodeRole generated by hbm2java
 */
@Entity
@Table(name = "SR_USER_CODE_ROLE", schema = "ALICE")
public class SrUserCodeRole implements java.io.Serializable {

	private int id;
	private String value;
	private Set<SrUser> srUsers = new HashSet<SrUser>(0);

	public SrUserCodeRole() {
	}

	public SrUserCodeRole(int id) {
		this.id = id;
	}

	public SrUserCodeRole(int id, String value, Set<SrUser> srUsers) {
		this.id = id;
		this.value = value;
		this.srUsers = srUsers;
	}

	@Id
	@TableGenerator(name="TABLE_GEN", table="ALICE_ID", pkColumnName="ID_NAME", 
		valueColumnName="ID_COUNT", pkColumnValue="SR_USER_CODE_ROLE", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.TABLE, generator="TABLE_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "VALUE", length = 200)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "srUserCodeRole")
	public Set<SrUser> getSrUsers() {
		return this.srUsers;
	}

	public void setSrUsers(Set<SrUser> srUsers) {
		this.srUsers = srUsers;
	}

}
