DROP TABLE SR_REQUEST                   CASCADE CONSTRAINT;
DROP TABLE SR_REQUEST_CODE_STATUS       CASCADE CONSTRAINT;
DROP TABLE SR_USER                      CASCADE CONSTRAINT;
DROP TABLE SR_USER_CODE_ROLE            CASCADE CONSTRAINT;
DROP TABLE SR_COMPANY                   CASCADE CONSTRAINT;
DROP TABLE SR_COMPANY_CODE_DIVISION     CASCADE CONSTRAINT;
DROP TABLE SR_INSTALL                   CASCADE CONSTRAINT;
DROP TABLE SR_INSTALL_CODE_PRODUCT      CASCADE CONSTRAINT;
DROP TABLE SR_INSTALL_CODE_VERSION      CASCADE CONSTRAINT;
DROP TABLE SR_INSTALL_INFO              CASCADE CONSTRAINT;
DROP TABLE SR_INSTALL_INFO_CODE_NAME    CASCADE CONSTRAINT;
DROP TABLE SR_INSTALL_INFO_CODE_VALUE   CASCADE CONSTRAINT;

CREATE TABLE SR_REQUEST (
    id         number(8),
    title       varchar2(200),
    content     varchar2(4000),
    answer      varchar2(4000),
    progress    varchar2(4000),
    status      number(8),
    requested   date,
    completed   date,
    requester   number(8),
    manager     number(8),
    developer   number(8),
    install     number(8),
    company     number(8),
    CONSTRAINT PK_SR_REQUEST PRIMARY KEY (id)
)
/
CREATE TABLE SR_REQUEST_CODE_STATUS (
    id   number(8),
    value   varchar2(100),
    CONSTRAINT PK_SR_REQUEST_CODE_STATUS PRIMARY KEY (id)
)
/
CREATE TABLE SR_USER (
    id     number(8),
    name    varchar2(100),
    role    number(8),
    company number(8),
    dept    varchar2(100),
    pos     varchar2(100),
    contact varchar2(100),
    email   varchar2(100),
    CONSTRAINT PK_SR_USER PRIMARY KEY (id)
)
/
CREATE TABLE SR_USER_CODE_ROLE (
	id   number(8),
	value   varchar2(200),
    CONSTRAINT PK_SR_USER_CODE_ROLE PRIMARY KEY (id)
)
/
CREATE TABLE SR_COMPANY (
    id         number(8),
    name        varchar2(100),
    division    number(8),
    ceo         varchar2(100),
    phone       varchar2(100),
    address     varchar2(200),
    web         varchar2(100),
    install     number(8),
    registed    date,
    register    number(8),
    CONSTRAINT PK_SR_COMPANY PRIMARY KEY (id)
)
/
CREATE TABLE SR_COMPANY_CODE_DIVISION (
	id   number(8),
	value   varchar2(100),
    CONSTRAINT PK_SR_COMPANY_CODE_DIVISION PRIMARY KEY (id)
)
/
CREATE TABLE SR_INSTALL (
    id         number(8),
    product     number(8),
    version     number(8),
    installer   number(8),
    manager     number(8),
    installed   date,
    CONSTRAINT PK_SR_INSTALL PRIMARY KEY (id)
)
/
CREATE TABLE SR_INSTALL_CODE_PRODUCT (
	id   number(8),
	value   varchar2(100),
    CONSTRAINT PK_SR_INSTALL_CODE_PRODUCT PRIMARY KEY (id)
)
/
CREATE TABLE SR_INSTALL_CODE_VERSION (
	id   number(8),
	product   number(8),
	value   varchar2(100),
    CONSTRAINT PK_SR_INSTALL_CODE_VERSION PRIMARY KEY (id)
)
/
CREATE TABLE SR_INSTALL_INFO (
    id    number(8),
    install number(8),
    name    number(8),
    value   number(8),
    CONSTRAINT PK_SR_INSTALL_INFO PRIMARY KEY (id)
)
/
CREATE TABLE SR_INSTALL_INFO_CODE_NAME (
	id  number(8),
	value   varchar2(200),
    CONSTRAINT PK_SR_INSTALL_INFO_CODE_NAME PRIMARY KEY (id)
)
/
CREATE TABLE SR_INSTALL_INFO_CODE_VALUE	(	
	id  number(8),
	name  number(8),
	value   varchar2(2000),
    CONSTRAINT PK_SR_INSTALL_INFO_CODE_VALUE PRIMARY KEY (id)
)
/

ALTER TABLE SR_REQUEST
ADD CONSTRAINT FK_SR_REQUEST_STATUS     FOREIGN KEY (status)    REFERENCES SR_REQUEST_CODE_STATUS (id)
/
ALTER TABLE SR_REQUEST
ADD CONSTRAINT FK_SR_REQUEST_requester  FOREIGN KEY (requester) REFERENCES SR_USER (id)
/
ALTER TABLE SR_REQUEST
ADD CONSTRAINT FK_SR_REQUEST_manager    FOREIGN KEY (manager)   REFERENCES SR_USER (id)
/
ALTER TABLE SR_REQUEST
ADD CONSTRAINT FK_SR_REQUEST_developer  FOREIGN KEY (developer) REFERENCES AUTH_USER (userid)
/
ALTER TABLE SR_REQUEST
ADD CONSTRAINT FK_SR_REQUEST_install    FOREIGN KEY (install)   REFERENCES SR_INSTALL (id)
/
ALTER TABLE SR_REQUEST
ADD CONSTRAINT FK_SR_REQUEST_company    FOREIGN KEY (company)   REFERENCES SR_COMPANY (id)
/
ALTER TABLE SR_USER
ADD CONSTRAINT FK_SR_USER_role      FOREIGN KEY (role)      REFERENCES SR_USER_CODE_ROLE (id)
/
ALTER TABLE SR_USER
ADD CONSTRAINT FK_SR_USER_company   FOREIGN KEY (company)   REFERENCES SR_COMPANY (id)
/
ALTER TABLE SR_COMPANY
ADD CONSTRAINT FK_SR_COMPANY_division  FOREIGN KEY (division)  REFERENCES SR_COMPANY_CODE_DIVISION (id)
/
ALTER TABLE SR_COMPANY
ADD CONSTRAINT FK_SR_COMPANY_install   FOREIGN KEY (install)   REFERENCES SR_INSTALL (id)
/
ALTER TABLE SR_COMPANY
ADD CONSTRAINT FK_SR_COMPANY_register  FOREIGN KEY (register)  REFERENCES SR_USER (id)
/
ALTER TABLE SR_INSTALL
ADD CONSTRAINT FK_SR_INSTALL_product    FOREIGN KEY (product)   REFERENCES SR_INSTALL_CODE_PRODUCT (id)
/
ALTER TABLE SR_INSTALL
ADD CONSTRAINT FK_SR_INSTALL_version    FOREIGN KEY (version)   REFERENCES SR_INSTALL_CODE_VERSION (id)
/
ALTER TABLE SR_INSTALL
ADD CONSTRAINT FK_SR_INSTALL_installer  FOREIGN KEY (installer) REFERENCES SR_USER (id)
/
ALTER TABLE SR_INSTALL
ADD CONSTRAINT FK_SR_INSTALL_manager    FOREIGN KEY (manager)   REFERENCES SR_USER (id)
/
ALTER TABLE SR_INSTALL_CODE_VERSION
ADD CONSTRAINT FK_SR_INSTALL_CODE_VER_prod      FOREIGN KEY (product)      REFERENCES SR_INSTALL_CODE_PRODUCT (id)
/
ALTER TABLE SR_INSTALL_INFO
ADD CONSTRAINT FK_INSTALL_INFO_install    FOREIGN KEY (install)  REFERENCES SR_INSTALL (id)
/
ALTER TABLE SR_INSTALL_INFO
ADD CONSTRAINT FK_INSTALL_INFO_name       FOREIGN KEY (name)     REFERENCES SR_INSTALL_INFO_CODE_NAME (id)
/
ALTER TABLE SR_INSTALL_INFO
ADD CONSTRAINT FK_INSTALL_INFO_value      FOREIGN KEY (value)    REFERENCES SR_INSTALL_INFO_CODE_VALUE (id)
/
ALTER TABLE SR_INSTALL_INFO_CODE_VALUE
ADD CONSTRAINT FK_SR_INSTALL_INFO_CD_VAL_name FOREIGN KEY (name)   REFERENCES SR_INSTALL_INFO_CODE_NAME (id)
/