
  CREATE TABLE "KAMORU"."BBS" 
   (	"BBSID" NUMBER NOT NULL ENABLE, 
	"TAGS" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"CONTENT" CLOB NOT NULL ENABLE, 
	"CREATOR" VARCHAR2(20 BYTE), 
	"CREATDTIME" DATE DEFAULT sysdate, 
	"HIT" NUMBER DEFAULT 0, 
	"STATE" CHAR(1 BYTE) DEFAULT 'N', 
	"MODIFIER" VARCHAR2(20 BYTE), 
	"MODIFYDTIME" DATE, 
	 CONSTRAINT "BBS_PK" PRIMARY KEY ("BBSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "KAMORU"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "KAMORU" 
 LOB ("CONTENT") STORE AS (
  TABLESPACE "KAMORU" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
 

  CREATE OR REPLACE TRIGGER "KAMORU"."BBS_AI" 
BEFORE INSERT ON BBS
REFERENCING new as new old as old
FOR EACH ROW
DECLARE
	TEMP_SEQ number(10);
BEGIN
	IF :old.bbsid IS NULL THEN
		SELECT seq_bbsid.NEXTVAL
			INTO TEMP_SEQ
			FROM DUAL;

		:new.bbsid := TEMP_SEQ;
	END IF;
EXCEPTION
	WHEN OTHERS THEN
		RAISE_APPLICATION_ERROR(-999999, 'UNHANDLED EXCEPTION');
END;

/
ALTER TRIGGER "KAMORU"."BBS_AI" ENABLE;
 
