/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test
 * Method:    getHello
 * Signature: (IF)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Test_getHello
  (JNIEnv *, jobject, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
