
  CREATE TABLE "KAMORU"."BBS_TAG" 
   (	"TAGID" NUMBER NOT NULL ENABLE, 
	"TAGNAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"STATUS" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"CREATEDTIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "BBS_TAG_PK" PRIMARY KEY ("TAGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "KAMORU"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "KAMORU" ;
 
