package com.hs.alice.sr.domain;

// Generated 2013. 4. 29 오후 2:46:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * SrCompanyCodeDivision generated by hbm2java
 */
@Entity
@Table(name = "SR_COMPANY_CODE_DIVISION", schema = "ALICE")
public class SrCompanyCodeDivision implements java.io.Serializable {

	private int id;
	private String value;
	private Set<SrCompany> srCompanies = new HashSet<SrCompany>(0);

	public SrCompanyCodeDivision() {
	}

	public SrCompanyCodeDivision(int id) {
		this.id = id;
	}

	public SrCompanyCodeDivision(int id, String value,
			Set<SrCompany> srCompanies) {
		this.id = id;
		this.value = value;
		this.srCompanies = srCompanies;
	}

	@Id
	@TableGenerator(name="TABLE_GEN", table="ALICE_ID", pkColumnName="ID_NAME", 
		valueColumnName="ID_COUNT", pkColumnValue="SR_COMPANY_CODE_DIVISION", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.TABLE, generator="TABLE_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "VALUE", length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "srCompanyCodeDivision")
	public Set<SrCompany> getSrCompanies() {
		return this.srCompanies;
	}

	public void setSrCompanies(Set<SrCompany> srCompanies) {
		this.srCompanies = srCompanies;
	}

}
