package com.hs.alice.sr.domain;

// Generated 2013. 4. 29 오후 2:46:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * SrInstallCodeProduct generated by hbm2java
 */
@Entity
@Table(name = "SR_INSTALL_CODE_PRODUCT", schema = "ALICE")
public class SrInstallCodeProduct implements java.io.Serializable {

	private int id;
	private String value;
	private Set<SrInstall> srInstalls = new HashSet<SrInstall>(0);
	private Set<SrInstallCodeVersion> srInstallCodeVersions = new HashSet<SrInstallCodeVersion>(
			0);

	public SrInstallCodeProduct() {
	}

	public SrInstallCodeProduct(int id) {
		this.id = id;
	}

	public SrInstallCodeProduct(int id, String value,
			Set<SrInstall> srInstalls,
			Set<SrInstallCodeVersion> srInstallCodeVersions) {
		this.id = id;
		this.value = value;
		this.srInstalls = srInstalls;
		this.srInstallCodeVersions = srInstallCodeVersions;
	}

	@Id
	@TableGenerator(name="TABLE_GEN", table="ALICE_ID", pkColumnName="ID_NAME", 
		valueColumnName="ID_COUNT", pkColumnValue="SR_INSTALL_CODE_PRODUCT", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.TABLE, generator="TABLE_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "VALUE", length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "srInstallCodeProduct")
	public Set<SrInstall> getSrInstalls() {
		return this.srInstalls;
	}

	public void setSrInstalls(Set<SrInstall> srInstalls) {
		this.srInstalls = srInstalls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "srInstallCodeProduct")
	public Set<SrInstallCodeVersion> getSrInstallCodeVersions() {
		return this.srInstallCodeVersions;
	}

	public void setSrInstallCodeVersions(
			Set<SrInstallCodeVersion> srInstallCodeVersions) {
		this.srInstallCodeVersions = srInstallCodeVersions;
	}

}
