package com.hs.alice.sr.domain;

// Generated 2013. 4. 29 오후 2:46:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SrRequest generated by hbm2java
 */
@Entity
@Table(name = "SR_REQUEST", schema = "ALICE")
public class SrRequest implements java.io.Serializable {

	private int id;
	private SrRequestCodeStatus srRequestCodeStatus;
	private SrUser srUserByRequester;
	private SrInstall srInstall;
	private SrUser srUserByManager;
	private SrCompany srCompany;
	private String title;
	private String content;
	private String answer;
	private String progress;
	private Date requested;
	private Date completed;
	private Integer developer;

	public SrRequest() {
	}

	public SrRequest(int id) {
		this.id = id;
	}

	public SrRequest(int id, SrRequestCodeStatus srRequestCodeStatus,
			SrUser srUserByRequester, SrInstall srInstall,
			SrUser srUserByManager, SrCompany srCompany, String title,
			String content, String answer, String progress, Date requested,
			Date completed, Integer developer) {
		this.id = id;
		this.srRequestCodeStatus = srRequestCodeStatus;
		this.srUserByRequester = srUserByRequester;
		this.srInstall = srInstall;
		this.srUserByManager = srUserByManager;
		this.srCompany = srCompany;
		this.title = title;
		this.content = content;
		this.answer = answer;
		this.progress = progress;
		this.requested = requested;
		this.completed = completed;
		this.developer = developer;
	}

	@Id
	@TableGenerator(name="TABLE_GEN", table="ALICE_ID", pkColumnName="ID_NAME", 
		valueColumnName="ID_COUNT", pkColumnValue="SR_REQUEST", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.TABLE, generator="TABLE_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS")
	public SrRequestCodeStatus getSrRequestCodeStatus() {
		return this.srRequestCodeStatus;
	}

	public void setSrRequestCodeStatus(SrRequestCodeStatus srRequestCodeStatus) {
		this.srRequestCodeStatus = srRequestCodeStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQUESTER")
	public SrUser getSrUserByRequester() {
		return this.srUserByRequester;
	}

	public void setSrUserByRequester(SrUser srUserByRequester) {
		this.srUserByRequester = srUserByRequester;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INSTALL")
	public SrInstall getSrInstall() {
		return this.srInstall;
	}

	public void setSrInstall(SrInstall srInstall) {
		this.srInstall = srInstall;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANAGER")
	public SrUser getSrUserByManager() {
		return this.srUserByManager;
	}

	public void setSrUserByManager(SrUser srUserByManager) {
		this.srUserByManager = srUserByManager;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANY")
	public SrCompany getSrCompany() {
		return this.srCompany;
	}

	public void setSrCompany(SrCompany srCompany) {
		this.srCompany = srCompany;
	}

	@Column(name = "TITLE", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "CONTENT", length = 4000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "ANSWER", length = 4000)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Column(name = "PROGRESS", length = 4000)
	public String getProgress() {
		return this.progress;
	}

	public void setProgress(String progress) {
		this.progress = progress;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REQUESTED", length = 7)
	public Date getRequested() {
		return this.requested;
	}

	public void setRequested(Date requested) {
		this.requested = requested;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "COMPLETED", length = 7)
	public Date getCompleted() {
		return this.completed;
	}

	public void setCompleted(Date completed) {
		this.completed = completed;
	}

	@Column(name = "DEVELOPER", precision = 8, scale = 0)
	public Integer getDeveloper() {
		return this.developer;
	}

	public void setDeveloper(Integer developer) {
		this.developer = developer;
	}

}
