package com.hs.alice.sr.domain;

// Generated 2013. 4. 29 오후 2:46:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * SrRequestCodeStatus generated by hbm2java
 */
@Entity
@Table(name = "SR_REQUEST_CODE_STATUS", schema = "ALICE")
public class SrRequestCodeStatus implements java.io.Serializable {

	private int id;
	private String value;
	private Set<SrRequest> srRequests = new HashSet<SrRequest>(0);

	public SrRequestCodeStatus() {
	}

	public SrRequestCodeStatus(int id) {
		this.id = id;
	}

	public SrRequestCodeStatus(int id, String value, Set<SrRequest> srRequests) {
		this.id = id;
		this.value = value;
		this.srRequests = srRequests;
	}

	@Id
	@TableGenerator(name="TABLE_GEN", table="ALICE_ID", pkColumnName="ID_NAME", 
		valueColumnName="ID_COUNT", pkColumnValue="SR_REQUEST_CODE_STATUS", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.TABLE, generator="TABLE_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "VALUE", length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "srRequestCodeStatus")
	public Set<SrRequest> getSrRequests() {
		return this.srRequests;
	}

	public void setSrRequests(Set<SrRequest> srRequests) {
		this.srRequests = srRequests;
	}

}
