package com.hs.alice.domain;

// Generated 2013. 4. 10 오전 10:19:22 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.hs.alice.core.AliceCore;

/**
 * AuthRoleGroupMap generated by hbm2java
 */
public class AuthRoleGroupMap implements java.io.Serializable {

	private static final long serialVersionUID = AliceCore.SERIAL_VERSION_UID;

    private static final Log logger = LogFactory.getLog(AuthRoleGroupMap.class);
	
	private BigDecimal mapid;
	private AuthGroup authGroup;
	private AuthRole authRole;

	public AuthRoleGroupMap() {
	}

	public AuthRoleGroupMap(BigDecimal mapid, AuthGroup authGroup,
			AuthRole authRole) {
		this.mapid = mapid;
		this.authGroup = authGroup;
		this.authRole = authRole;
	}

	public void initialize() {
		toString();
	}
	
	public BigDecimal getMapid() {
		return this.mapid;
	}

	public void setMapid(BigDecimal mapid) {
		this.mapid = mapid;
	}

	public AuthGroup getAuthGroup() {
		return this.authGroup;
	}

	public void setAuthGroup(AuthGroup authGroup) {
		this.authGroup = authGroup;
	}

	public AuthRole getAuthRole() {
		return this.authRole;
	}

	public void setAuthRole(AuthRole authRole) {
		this.authRole = authRole;
	}

	@Override
	public String toString() {
		return "AuthRoleGroupMap [mapid=" + mapid + ", authGroup=" + authGroup.getGroupid() + ":" + authGroup.getGroupname()
				+ ", authRole=" + authRole.getRoleid() + ":" + authRole.getRolename() + "]";
	}

	
}
