<ul>
	<li><a href="<c:url value="/"/>">Home</a>
	<li><a href="<c:url value="/video"/>">Video Main</a>
	<li><a href="<c:url value="/video/search"/>">Video search</a>
	<li><a href="<c:url value="/video/history"/>">Video history</a>
	<li><a href="<c:url value="/video/list"/>">Video list</a>
	<li><a href="<c:url value="/video/actress"/>">Actress list</a>
	<li><a href="<c:url value="/video/studio"/>">Studio List</a>
	<li><a href="<c:url value="/image"/>">Image view</a>
	<li><a href="<c:url value="/requestMappingList"/>">request mapping list</a>
	<li><a href="<c:url value="/jsp/util/sessionView.jsp"/>">Web Session</a>
	<li><a href="<c:url value="/jsp/colors.jsp"/>">Standard Colors</a>
	<li><a href="<c:url value="/jsp/util/threaddump.jsp"/>">Thread dump</a>
	<li><a href="<c:url value="/jsp/pic/imgView.html"/>">Canvas Image view</a>
	
</ul>
<c:url value=""/>